# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arakan | Eyalet-i Myanmar
email: 
description:
  - Ağırlıklı olarak Müslüman bir topluluk olan Rohingya soykırım ile yok edilmek isteniyor<br>
  - Rakhine'e müdahale etmek için uluslararası bir istek yok; daha önce mevcut değildi <br>
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title.html
url: "../" 
github_username:

# Build settings
markdown: kramdown
